### ISSUE TITLE
Treatment of strings (uppercase vs. lovercase)

### ISSUE THREAD

**Issue by raback** [tapegoji/elmer-spice#1]
I see there is some bits in the code related to 'Fluid' vs. 'fluid'. By default Elmer changes strings to lowercase when they are of type "string" but does not when they are of type "file". The "name" of an entity is of type "string" so the uppercase is lost on the way. If you would have a special keyword for preCISE it could have the type "file" if needed. Just a comment, no need for action.

**Comment by tapegoji** [comment]
Thank you Peter. Will keep this in mind and update the code accordingly.

**Comment by tapegoji** [comment]
updated the code to reflect this recommendation.
